networks:
  card-network:
    driver: bridge

services:
  card-postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: card-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 54321:5432
    networks:
      - card-network

  card-api:
    build: ./card-api
    environment:
      DB_HOST: jdbc:postgresql://card-postgres:5432/card-db?useSSL=false&serverTimezone=America/Sao_Paulo
      DB_USER: postgres
      DB_PASSWORD: 123456
    ports:
      - 8080:8080
    networks:
      - card-network
    depends_on:
      - card-postgres

  card-frontend:
    build: ./mibess-cards
    image: card-frontend:v1
    environment:
      API_BASE_URL: http://card-api:8080
    ports:
      - 4200:4200
    networks:
      - card-network
    depends_on:
      - card-api

  card-proxy:
    build: ./nginx
    image: card-proxy
    ports:
      - 80:80
    networks:
      - card-network
    depends_on:
      - card-api
